=== OrcaBus/service-workflow-manager/docs/events/WorkflowRunStateChange/WorkflowRunStateChange.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$id": "https://raw.githubusercontent.com/OrcaBus/service-workflow-manager/refs/heads/main/docs/events/WorkflowRunStateChange/WorkflowRunStateChange.schema.json",
  "description": "EventBridge custom event schema for WorkflowRunStateChange events",
  "title": "AWSEvent",
  "definitions": {
    "WorkflowRunStateChange": {
      "type": "object",
      "required": [
        "id",
        "version",
        "timestamp",
        "orcabusId",
        "portalRunId",
        "workflowRunName",
        "workflow",
        "status"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "timestamp": {
          "type": "string",
          "format": "date-time"
        },
        "orcabusId": {
          "type": "string"
        },
        "portalRunId": {
          "type": "string"
        },
        "executionId": {
          "type": "string"
        },
        "workflowRunName": {
          "type": "string"
        },
        "workflow": {
          "$ref": "#/definitions/Workflow"
        },
        "analysisRun": {
          "$ref": "#/definitions/AnalysisRun"
        },
        "libraries": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Library"
          }
        },
        "computeEnv": {
          "type": "string"
        },
        "storageEnv": {
          "type": "string"
        },
        "status": {
          "type": "string"
        },
        "createdBy": {
          "type": "string"
        },
        "payload": {
          "$ref": "#/definitions/Payload"
        }
      }
    },
    "Library": {
      "type": "object",
      "required": [
        "libraryId",
        "orcabusId"
      ],
      "properties": {
        "libraryId": {
          "type": "string"
        },
        "orcabusId": {
          "type": "string"
        },
        "readsets": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Readset"
          }
        }
      }
    },
    "Readset": {
      "type": "object",
      "required": [
        "orcabusId",
        "rgid"
      ],
      "properties": {
        "orcabusId": {
          "type": "string"
        },
        "rgid": {
          "type": "string"
        }
      }
    },
    "Workflow": {
      "type": "object",
      "required": [
        "orcabusId",
        "name",
        "version",
        "codeVersion",
        "executionEngine"
      ],
      "properties": {
        "orcabusId": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "codeVersion": {
          "type": "string"
        },
        "executionEngine": {
          "type": "string"
        },
        "executionEnginePipelineId": {
          "type": "string"
        },
        "validationState": {
          "type": "string"
        }
      }
    },
    "AnalysisRun": {
      "type": "object",
      "required": [
        "orcabusId",
        "name"
      ],
      "properties": {
        "orcabusId": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "Payload": {
      "type": "object",
      "required": [
        "orcabusId",
        "refId",
        "version",
        "data"
      ],
      "properties": {
        "orcabusId": {
          "type": "string"
        },
        "refId": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "data": {
          "type": "object"
        }
      }
    }
  },
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "region": {
      "type": "string"
    },
    "resources": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "source": {
      "type": "string"
    },
    "time": {
      "format": "date-time",
      "type": "string"
    },
    "version": {
      "type": "string"
    },
    "account": {
      "type": "string"
    },
    "detail-type": {
      "type": "string"
    },
    "detail": {
      "$ref": "#/definitions/WorkflowRunStateChange"
    }
  },
  "required": [
    "detail",
    "detail-type",
    "source"
  ]
}

=== OrcaBus/service-workflow-manager/docs/events/WorkflowRunStateChange/examples/WRSC__example1.json
{
  "version": "0",
  "id": "f71bbbbb-5b36-40c2-f7dc-804ca6270cd6",
  "detail-type": "WorkflowRunStateChange",
  "source": "orcabus.workflowmanager",
  "account": "123456789012",
  "time": "2024-05-01T09:25:44Z",
  "region": "ap-southeast-2",
  "resources": [],
  "detail": {
    "id": "<hash(values)> e.g. 97534601940f17ebcfee02e9df998244",
    "version": "1.1.0",
    "timestamp": "2025-05-01T09:25:44Z",
    "orcabusId": "wfr.<ULID> e.g. wfr.01J5M2J44HFJ9424G7074HHHHH",
    "portalRunId": "202405012397gatc",
    "workflowRunName": "<fill-by-workflow-manager> e.g. 540424_A01001_0193_BBBBMMDRX5 FASTQ Copy",
    "workflow": {
      "orcabusId": "wfl.01J5M2JFE1JPYV62RYQEG99CPW",
      "name": "<fill-by-workflow-manager> e.g. bssh_icav2_fastq_copy",
      "version": "<fill-by-workflow-manager> e.g. 1.2.3",
      "codeVersion": "<fill-by-workflow-manager> e.g. 0.0.0",
      "executionEngine": "<fill-by-workflow-manager> e.g. ICA",
      "executionEnginePipelineId": "<fill-by-workflow-manager> e.g. 123.456.789",
      "validationState": "UNVALIDATED"
    },
    "analysisRun": {
      "orcabusId": "anr.01J5M2JFE1JPYV62RYQEG99RUN",
      "name": "wgts-dna"
    },
    "libraries": [
      {
        "libraryId": "L000001",
        "orcabusId": "lib.01J5M2J44HFJ9424G7074NKTGN"
      },
      {
        "libraryId": "L000002",
        "orcabusId": "lib.01J5M2JFE1JPYV62RYQEG99CP5"
      }
    ],
    "status": "READY",
    "payload": {
      "orcabusId": "pld.<ULID> e.g. pld.01J5M2J44HFJ9424G7074PPPPP",
      "refId": "<fill-by-workflow-manager> e.g. <uuid>",
      "version": "0.1.0",
      "data": {
        "projectId": "bxxxxxxxx-dxxx-4xxxx-adcc-xxxxxxxxx",
        "executionId": "12345678-238c-4200-b632-d5dd8c8db94a",
        "outputUriPrefix": "icav2://12345678-32d3-4c76-a324-c6a85dae87b5/ilmn_primary/"
      }
    }
  }
}

=== OrcaBus/service-workflow-manager/docs/events/WorkflowRunStateChange/examples/WRSC__example2.json
{
  "version": "0",
  "id": "f71bbbbb-5b36-40c2-f7dc-804ca6270cd6",
  "detail-type": "WorkflowRunStateChange",
  "source": "orcabus.workflowmanager",
  "account": "123456789012",
  "time": "2024-05-01T09:25:44Z",
  "region": "ap-southeast-2",
  "resources": [],
  "detail": {
    "id": "<hash(values)> e.g. 97534601940f17ebcfee02e9df998244",
    "version": "1.1.0",
    "timestamp": "2025-05-01T09:25:44Z",
    "orcabusId": "wfr.<ULID> e.g. wfr.01J5M2J44HFJ9424G7074HHHHH",
    "portalRunId": "202405012397gatc",
    "workflowRunName": "<fill-by-workflow-manager> e.g. 540424_A01001_0193_BBBBMMDRX5 FASTQ Copy",
    "workflow": {
      "orcabusId": "wfl.01J5M2JFE1JPYV62RYQEG99CPW",
      "name": "<fill-by-workflow-manager> e.g. bssh_icav2_fastq_copy",
      "version": "<fill-by-workflow-manager> e.g. 1.2.3",
      "codeVersion": "<fill-by-workflow-manager> e.g. 0.0.0",
      "executionEngine": "<fill-by-workflow-manager> e.g. ICA",
      "executionEnginePipelineId": "<fill-by-workflow-manager> e.g. 123.456.789",
      "validationState": "UNVALIDATED"
    },
    "status": "DEPRECATED",
    "stateCreatedBy": "user@example.com"
  }
}
